server:
  port: 8190
  servlet:
    context-path: /web-market-carts
integrations:
  product-service:
    url: http://localhost:8189/web-market-core/
    connect-timeout: 5000
    read-timeout: 10000
    write-timeout: 5000